chore(conf): fix pr scope checking logic

diff --git a/.github/workflows/lint-pr.yml b/.github/workflows/lint-pr.yml
--- a/.github/workflows/lint-pr.yml
+++ b/.github/workflows/lint-pr.yml
@@ -2,10 +2,7 @@ name: "Lint PR"
 
 on:
   pull_request_target:
-    types:
-      - opened
-      - edited
-      - synchronize
+    types: [opened, edited, synchronize]
 
 jobs:
   lint-title:
@@ -17,12 +14,21 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   check-scope:
-    if: github.ref_name != 'dev' && github.base_ref == 'master'
-    name: Validate PR Base Ref
+    name: Validate PR Scope
     runs-on: ubuntu-latest
 
     steps:
-      - name: Error Message
+      - name: Wrong Branch Scope
         run: |
-          echo "The branch ${{ github.ref_name }} should not point to the master branch."
-          exit 1
+          echo "Checking PR source and target branches"
+          PR_BASE_BRANCH=$(jq -r .pull_request.base.ref < "${GITHUB_EVENT_PATH}")
+          PR_HEAD_BRANCH=$(jq -r .pull_request.head.ref < "${GITHUB_EVENT_PATH}")
+          echo "PR Base Branch: $PR_BASE_BRANCH"
+          echo "PR Head Branch: $PR_HEAD_BRANCH"
+          if [ "$PR_BASE_BRANCH" == "master" ] && [ "$PR_HEAD_BRANCH" != "dev" ]; then
+            echo "Error: The branch `$PR_HEAD_BRANCH` should not point to the `master` branch."
+            echo "Error: Please change the base branch to `dev`."
+            exit 1
+          else
+            echo "Branch check passed."
+          fi
